# -*- coding: utf-8 -*-
"""user_input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mroz7xgMzR21d5nMe9VqT4Z9p4Ga_j_T
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tokenizers import Tokenizer

tokenizer = Tokenizer.from_file("/content/minigpt_tokenizer (1).json")

vocab_size = tokenizer.get_vocab_size()

block_size = 128
n_embd = 256
n_head = 4
n_layer = 6
dropout = 0.1


class SelfAttention(layers.Layer):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.attention = layers.MultiHeadAttention(
            num_heads=n_head,
            key_dim=n_embd // n_head,
            dropout=dropout
        )

        self.proj = layers.Dense(n_embd)

        self.dropout_layer = layers.Dropout(dropout)

        self.ln = layers.LayerNormalization()

    def call(self, x):

        attn_output = self.attention(
            x,
            x,
            use_causal_mask=True
        )

        attn_output = self.dropout_layer(attn_output)

        return self.ln(x + attn_output)


class FeedForward(layers.Layer):

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

        self.net = keras.Sequential([
            layers.Dense(4 * n_embd, activation="gelu"),
            layers.Dense(n_embd),
            layers.Dropout(dropout)
        ])

    def call(self, x):

        return self.net(x)


class Block(layers.Layer):

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

        self.ln1 = layers.LayerNormalization()

        self.atten = SelfAttention()

        self.ln2 = layers.LayerNormalization()

        self.ffn = FeedForward()

    def call(self, x):

        attn_output = self.atten(self.ln1(x))

        x = x + attn_output

        ffn_output = self.ffn(self.ln2(x))

        x = x + ffn_output

        return x


class MiniGPT(keras.Model):

    def __init__(self, **kwargs):

        super().__init__(**kwargs)

        self.token_embedding = layers.Embedding(
            vocab_size,
            n_embd
        )

        self.position_embedding = layers.Embedding(
            block_size,
            n_embd
        )

        self.blocks = [
            Block()
            for _ in range(n_layer)
        ]

        self.ln_f = layers.LayerNormalization()

        self.lm_head = layers.Dense(vocab_size)

    def call(self, idx):

        B = tf.shape(idx)[0]

        T = tf.shape(idx)[1]

        tok_emb = self.token_embedding(idx)

        pos = tf.range(T)

        pos_emb = self.position_embedding(pos)

        x = tok_emb + pos_emb

        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)

        logits = self.lm_head(x)

        return logits


model = tf.keras.models.load_model(
    "/content/minigpt.keras",
    custom_objects={
        "MiniGPT": MiniGPT,
        "Block": Block,
        "SelfAttention": SelfAttention,
        "FeedForward": FeedForward
    },
    compile=False
)

def generate_text(prompt, max_new_tokens=50, temperature=0.8):

    tokens = tokenizer.encode(prompt).ids

    for _ in range(max_new_tokens):

        context = tokens[-block_size:]

        x = tf.constant([context], dtype=tf.int32)

        logits = model(x)

        logits = logits[:, -1, :]

        logits = logits / temperature

        probs = tf.nn.softmax(logits)

        next_token = tf.random.categorical(
            tf.math.log(probs),
            num_samples=1
        )[0, 0].numpy()

        tokens.append(int(next_token))

    return tokenizer.decode(tokens)


print(generate_text("time", 80,0.1))